<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="Harrisons-iMac.local" name="testcases.TestCase1" tests="4" failures="2" timestamp="21 Jul 2020 23:44:51 GMT" time="0.037" errors="0">
  <testcase name="doUserReg" time="0.012" classname="testcases.TestCase1">
    <failure type="java.lang.AssertionError" message="User Reg Test Failed">
      <![CDATA[java.lang.AssertionError: User Reg Test Failed
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at testcases.TestCase1.doUserReg(TestCase1.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- doUserReg -->
  <testcase name="isSkip" time="0.000" classname="testcases.TestCase1">
    <skipped/>
  </testcase> <!-- isSkip -->
  <testcase name="tearDown" time="0.005" classname="testcases.TestCase1">
    <failure type="java.lang.AssertionError" message="&lt;details&gt;&lt;summary&gt;&lt;b&gt;&lt;font color=red&gt;Exception Occured:Click to see&lt;/font&gt;&lt;/b &gt;&lt;/summary&gt;[org.testng.AssertJUnit.fail(AssertJUnit.java:59)&lt;br&gt; testcases.TestCase1.doUserReg(TestCase1.java:70)&lt;br&gt; sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br&gt; sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&lt;br&gt; sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&lt;br&gt; java.lang.reflect.Method.invoke(Method.java:498)&lt;br&gt; org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)&lt;br&gt; org.testng.internal.Invoker.invokeMethod(Invoker.java:583)&lt;br&gt; org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)&lt;br&gt; org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)&lt;br&gt; org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)&lt;br&gt; org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)&lt;br&gt; org.testng.TestRunner.privateRun(TestRunner.java:648)&lt;br&gt; org.testng.TestRunner.run(TestRunner.java:505)&lt;br&gt; org.testng.SuiteRunner.runTest(SuiteRunner.java:455)&lt;br&gt; org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)&lt;br&gt; org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)&lt;br&gt; org.testng.SuiteRunner.run(SuiteRunner.java:364)&lt;br&gt; org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)&lt;br&gt; org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)&lt;br&gt; org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)&lt;br&gt; org.testng.TestNG.runSuitesLocally(TestNG.java:1137)&lt;br&gt; org.testng.TestNG.runSuites(TestNG.java:1049)&lt;br&gt; org.testng.TestNG.run(TestNG.java:1017)&lt;br&gt; org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)&lt;br&gt; org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)&lt;br&gt; org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]&lt;/details&gt; 
">
      <![CDATA[java.lang.AssertionError: <details><summary><b><font color=red>Exception Occured:Click to see</font></b ></summary>[org.testng.AssertJUnit.fail(AssertJUnit.java:59)<br> testcases.TestCase1.doUserReg(TestCase1.java:70)<br> sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.lang.reflect.Method.invoke(Method.java:498)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br> org.testng.internal.Invoker.invokeMethod(Invoker.java:583)<br> org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)<br> org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br> org.testng.TestRunner.privateRun(TestRunner.java:648)<br> org.testng.TestRunner.run(TestRunner.java:505)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br> org.testng.SuiteRunner.run(SuiteRunner.java:364)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br> org.testng.TestNG.runSuites(TestNG.java:1049)<br> org.testng.TestNG.run(TestNG.java:1017)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details> 

at org.testng.Assert.fail(Assert.java:96)
at testcases.TestCase1.tearDown(TestCase1.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tearDown -->
  <testcase name="doLogin" time="0.020" classname="testcases.TestCase1"/>
</testsuite> <!-- testcases.TestCase1 -->
